package com.worksheet.auth;

import java.sql.*;
import java.time.Instant;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.springframework.web.server.ResponseStatusException;
import static org.springframework.http.HttpStatus.CONFLICT;

@Repository
public class UserRepository {
    private final String url;

    // An independent JDBC connection avoids changing the minigame's JPA datasource.
    public UserRepository(@Value("${app.auth.database-url}") String url) {
        this.url = url;
        try (var connection = connect(); var statement = connection.createStatement()) {
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS auth_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(254) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    created_at VARCHAR(40) NOT NULL
                )
                """);
        } catch (SQLException error) { throw databaseError(error); }
    }

    private Connection connect() throws SQLException {
        return DriverManager.getConnection(url, "sa", "");
    }

    public AuthUser create(String name, String email, String passwordHash) {
        Instant createdAt = Instant.now();
        try (var connection = connect(); var statement = connection.prepareStatement(
                "INSERT INTO auth_users (name, email, password_hash, created_at) VALUES (?, ?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, name);
            statement.setString(2, email);
            statement.setString(3, passwordHash);
            statement.setString(4, createdAt.toString());
            statement.executeUpdate();
            try (var keys = statement.getGeneratedKeys()) {
                if (!keys.next()) throw new SQLException("Missing generated user ID");
                return new AuthUser(keys.getLong(1), name, email, createdAt);
            }
        } catch (SQLException error) {
            if ("23505".equals(error.getSQLState())) {
                throw new ResponseStatusException(CONFLICT, "An account with this email already exists.");
            }
            throw databaseError(error);
        }
    }

    public Optional<StoredUser> findByEmail(String email) {
        try (var connection = connect(); var statement = connection.prepareStatement(
                "SELECT * FROM auth_users WHERE email = ?")) {
            statement.setString(1, email);
            try (var result = statement.executeQuery()) {
                return result.next() ? Optional.of(new StoredUser(readUser(result), result.getString("password_hash")))
                    : Optional.empty();
            }
        } catch (SQLException error) { throw databaseError(error); }
    }

    public Optional<AuthUser> findById(long id) {
        try (var connection = connect(); var statement = connection.prepareStatement(
                "SELECT id, name, email, created_at FROM auth_users WHERE id = ?")) {
            statement.setLong(1, id);
            try (var result = statement.executeQuery()) {
                return result.next() ? Optional.of(readUser(result)) : Optional.empty();
            }
        } catch (SQLException error) { throw databaseError(error); }
    }

    private AuthUser readUser(ResultSet result) throws SQLException {
        return new AuthUser(result.getLong("id"), result.getString("name"), result.getString("email"),
            Instant.parse(result.getString("created_at")));
    }

    private IllegalStateException databaseError(SQLException error) {
        return new IllegalStateException("Unable to access the authentication database", error);
    }

    public record StoredUser(AuthUser user, String passwordHash) {}
}
