CREATE TABLE classroom (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    join_code VARCHAR(12) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_classroom_teacher
        FOREIGN KEY (teacher_id) REFERENCES auth_users(id)
);

CREATE INDEX idx_classroom_teacher_id ON classroom(teacher_id);

CREATE TABLE classroom_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    left_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT fk_classroom_member_classroom
        FOREIGN KEY (classroom_id) REFERENCES classroom(id),
    CONSTRAINT fk_classroom_member_user
        FOREIGN KEY (user_id) REFERENCES auth_users(id),
    CONSTRAINT uq_classroom_member UNIQUE (classroom_id, user_id)
);

CREATE INDEX idx_classroom_member_user_id ON classroom_member(user_id);
