CREATE TABLE worksheet_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL,
    worksheet_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    classroom_id BIGINT,
    user_id BIGINT NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT fk_assignment_worksheet
        FOREIGN KEY (worksheet_id) REFERENCES worksheet(id),
    CONSTRAINT fk_assignment_teacher
        FOREIGN KEY (teacher_id) REFERENCES auth_users(id),
    CONSTRAINT fk_assignment_classroom
        FOREIGN KEY (classroom_id) REFERENCES classroom(id),
    CONSTRAINT fk_assignment_user
        FOREIGN KEY (user_id) REFERENCES auth_users(id),
    CONSTRAINT uq_assignment_batch_user UNIQUE (batch_id, user_id)
);

CREATE INDEX idx_assignment_teacher_id ON worksheet_assignment(teacher_id);
CREATE INDEX idx_assignment_user_id ON worksheet_assignment(user_id);
CREATE INDEX idx_assignment_classroom_user ON worksheet_assignment(classroom_id, user_id);
CREATE INDEX idx_assignment_worksheet_id ON worksheet_assignment(worksheet_id);

ALTER TABLE worksheet_result
    ADD COLUMN assignment_id BIGINT;

ALTER TABLE worksheet_result
    ADD CONSTRAINT fk_worksheet_result_assignment
        FOREIGN KEY (assignment_id) REFERENCES worksheet_assignment(id);

CREATE INDEX idx_worksheet_result_assignment_id ON worksheet_result(assignment_id);
