CREATE TABLE mini_game_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_mini_game_asset_size CHECK (size_bytes > 0),
    CONSTRAINT fk_mini_game_asset_owner
        FOREIGN KEY (owner_user_id) REFERENCES auth_users(id) ON DELETE RESTRICT
);

CREATE INDEX idx_mini_game_asset_owner ON mini_game_asset(owner_user_id);
