CREATE TABLE worksheet_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_id BIGINT NOT NULL,
    revision_number INT NOT NULL,
    name_snapshot VARCHAR(150) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_revision_worksheet FOREIGN KEY (worksheet_id) REFERENCES worksheet(id),
    CONSTRAINT ck_revision_number CHECK (revision_number > 0),
    CONSTRAINT uq_revision_number UNIQUE (worksheet_id, revision_number),
    CONSTRAINT uq_revision_hash UNIQUE (worksheet_id, content_hash)
);

CREATE TABLE worksheet_revision_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_revision_id BIGINT NOT NULL,
    source_worksheet_item_id BIGINT,
    mini_game_definition_id BIGINT NOT NULL,
    order_index INT NOT NULL,
    configuration JSONB NOT NULL,
    CONSTRAINT fk_revision_item_revision
        FOREIGN KEY (worksheet_revision_id) REFERENCES worksheet_revision(id) ON DELETE CASCADE,
    CONSTRAINT fk_revision_item_source
        FOREIGN KEY (source_worksheet_item_id) REFERENCES worksheet_item(id) ON DELETE SET NULL,
    CONSTRAINT fk_revision_item_definition
        FOREIGN KEY (mini_game_definition_id) REFERENCES mini_game_definition(id),
    CONSTRAINT ck_revision_item_order CHECK (order_index >= 0),
    CONSTRAINT uq_revision_item_order UNIQUE (worksheet_revision_id, order_index)
);

INSERT INTO worksheet_revision (worksheet_id, revision_number, name_snapshot, content_hash, published_at)
SELECT w.id,
       1,
       w.name,
       md5(w.name || '|' || COALESCE((
           SELECT string_agg(i.mini_game_id || ':' || i.order_index || ':' || i.configuration::text, '|' ORDER BY i.order_index)
           FROM worksheet_item i
           WHERE i.worksheet_id = w.id
       ), '')),
       w.updated_at
FROM worksheet w;

INSERT INTO worksheet_revision_item
    (worksheet_revision_id, source_worksheet_item_id, mini_game_definition_id, order_index, configuration)
SELECT r.id, i.id, i.mini_game_id, i.order_index, i.configuration
FROM worksheet_revision r
JOIN worksheet_item i ON i.worksheet_id = r.worksheet_id;

ALTER TABLE worksheet_assignment ADD COLUMN worksheet_revision_id BIGINT;

UPDATE worksheet_assignment a
SET worksheet_revision_id = r.id
FROM worksheet_revision r
WHERE r.worksheet_id = a.worksheet_id AND r.revision_number = 1;

ALTER TABLE worksheet_assignment ALTER COLUMN worksheet_revision_id SET NOT NULL;
ALTER TABLE worksheet_assignment
    ADD CONSTRAINT fk_assignment_revision
        FOREIGN KEY (worksheet_revision_id) REFERENCES worksheet_revision(id);

CREATE INDEX idx_revision_worksheet_published
    ON worksheet_revision(worksheet_id, published_at DESC);
CREATE INDEX idx_revision_item_revision_order
    ON worksheet_revision_item(worksheet_revision_id, order_index);
CREATE INDEX idx_assignment_revision_id
    ON worksheet_assignment(worksheet_revision_id);

DROP INDEX idx_assignment_teacher_id;
DROP INDEX idx_assignment_worksheet_id;
ALTER TABLE worksheet_assignment DROP CONSTRAINT fk_assignment_teacher;
ALTER TABLE worksheet_assignment DROP CONSTRAINT fk_assignment_worksheet;
ALTER TABLE worksheet_assignment DROP COLUMN teacher_id;
ALTER TABLE worksheet_assignment DROP COLUMN worksheet_id;
