CREATE TABLE worksheet_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_revision_id BIGINT NOT NULL,
    assignment_id BIGINT,
    status VARCHAR(20) NOT NULL,
    total_score INT NOT NULL DEFAULT 0,
    max_score INT NOT NULL DEFAULT 0,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_attempt_revision
        FOREIGN KEY (worksheet_revision_id) REFERENCES worksheet_revision(id),
    CONSTRAINT fk_attempt_assignment
        FOREIGN KEY (assignment_id) REFERENCES worksheet_assignment(id),
    CONSTRAINT ck_attempt_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT ck_attempt_scores CHECK (total_score >= 0 AND max_score >= 0 AND total_score <= max_score),
    CONSTRAINT ck_attempt_completion CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL)
    )
);

CREATE TABLE worksheet_attempt_item_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_attempt_id BIGINT NOT NULL,
    worksheet_revision_item_id BIGINT NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    score INT NOT NULL,
    max_score INT NOT NULL,
    time_seconds INT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_attempt_item_result_attempt
        FOREIGN KEY (worksheet_attempt_id) REFERENCES worksheet_attempt(id) ON DELETE CASCADE,
    CONSTRAINT fk_attempt_item_result_revision_item
        FOREIGN KEY (worksheet_revision_item_id) REFERENCES worksheet_revision_item(id),
    CONSTRAINT ck_attempt_item_outcome CHECK (outcome IN ('COMPLETED', 'SKIPPED')),
    CONSTRAINT ck_attempt_item_scores CHECK (
        score >= 0 AND max_score >= 0 AND score <= max_score
        AND (outcome <> 'SKIPPED' OR score = 0)
    ),
    CONSTRAINT ck_attempt_item_time CHECK (time_seconds >= 0),
    CONSTRAINT uq_attempt_revision_item UNIQUE (worksheet_attempt_id, worksheet_revision_item_id)
);

INSERT INTO worksheet_attempt
    (id, worksheet_revision_id, assignment_id, status, total_score, max_score, started_at, completed_at)
SELECT result.id,
       COALESCE(assignment.worksheet_revision_id, revision.id),
       result.assignment_id,
       'COMPLETED',
       result.total_score,
       result.max_score,
       result.completed_at,
       result.completed_at
FROM worksheet_result result
LEFT JOIN worksheet_assignment assignment ON assignment.id = result.assignment_id
LEFT JOIN LATERAL (
    SELECT r.id
    FROM worksheet_revision r
    WHERE r.worksheet_id = result.worksheet_id
    ORDER BY r.revision_number DESC
    LIMIT 1
) revision ON TRUE;

INSERT INTO worksheet_attempt_item_result
    (id, worksheet_attempt_id, worksheet_revision_item_id, outcome, score, max_score, time_seconds, details)
SELECT game_result.id,
       game_result.worksheet_result_id,
       revision_item.id,
       'COMPLETED',
       game_result.score,
       game_result.max_score,
       game_result.time_seconds,
       game_result.details
FROM mini_game_result game_result
JOIN worksheet_attempt attempt ON attempt.id = game_result.worksheet_result_id
JOIN worksheet_revision_item revision_item
  ON revision_item.worksheet_revision_id = attempt.worksheet_revision_id
 AND revision_item.source_worksheet_item_id = game_result.worksheet_item_id;

SELECT setval(pg_get_serial_sequence('worksheet_attempt', 'id'),
    COALESCE((SELECT MAX(id) FROM worksheet_attempt), 1),
    EXISTS (SELECT 1 FROM worksheet_attempt));
SELECT setval(pg_get_serial_sequence('worksheet_attempt_item_result', 'id'),
    COALESCE((SELECT MAX(id) FROM worksheet_attempt_item_result), 1),
    EXISTS (SELECT 1 FROM worksheet_attempt_item_result));

CREATE INDEX idx_attempt_revision_started
    ON worksheet_attempt(worksheet_revision_id, started_at DESC);
CREATE INDEX idx_attempt_assignment_started
    ON worksheet_attempt(assignment_id, started_at DESC);
CREATE INDEX idx_attempt_item_result_attempt
    ON worksheet_attempt_item_result(worksheet_attempt_id);
CREATE INDEX idx_active_membership
    ON classroom_member(classroom_id, user_id) WHERE left_at IS NULL;
CREATE INDEX idx_active_assignment_user
    ON worksheet_assignment(user_id, assigned_at DESC) WHERE revoked_at IS NULL;
