ALTER TABLE mini_game_definition
    ADD COLUMN description VARCHAR(500),
    ADD COLUMN thumbnail_asset_id BIGINT;

ALTER TABLE mini_game_asset
    ADD COLUMN sha256 VARCHAR(64),
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

UPDATE mini_game_asset SET sha256 = md5('legacy:' || storage_key) WHERE sha256 IS NULL;
ALTER TABLE mini_game_asset ALTER COLUMN sha256 SET NOT NULL;

ALTER TABLE mini_game_asset
    ADD CONSTRAINT ck_mini_game_asset_status CHECK (status IN ('ACTIVE', 'DELETED'));

ALTER TABLE mini_game_definition
    ADD CONSTRAINT fk_definition_thumbnail
        FOREIGN KEY (thumbnail_asset_id) REFERENCES mini_game_asset(id) ON DELETE SET NULL;

CREATE TABLE mini_game_definition_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mini_game_definition_id BIGINT NOT NULL,
    mini_game_asset_id BIGINT NOT NULL,
    asset_key VARCHAR(100) NOT NULL,
    CONSTRAINT uq_definition_asset_key UNIQUE (mini_game_definition_id, asset_key),
    CONSTRAINT uq_definition_asset UNIQUE (mini_game_definition_id, mini_game_asset_id),
    CONSTRAINT fk_definition_asset_definition
        FOREIGN KEY (mini_game_definition_id) REFERENCES mini_game_definition(id) ON DELETE CASCADE,
    CONSTRAINT fk_definition_asset_asset
        FOREIGN KEY (mini_game_asset_id) REFERENCES mini_game_asset(id) ON DELETE RESTRICT
);

CREATE INDEX idx_definition_asset_asset_id ON mini_game_definition_asset(mini_game_asset_id);
CREATE INDEX idx_definition_active_type_version
    ON mini_game_definition(active, type, version DESC);
