CREATE TABLE public.auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk6jqfsuvys3lan090p4mk16a5t UNIQUE (email)
);

CREATE TABLE public.minigame1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    image_content_type VARCHAR(255),
    image_filename VARCHAR(255),
    name VARCHAR(255)
);
