CREATE TABLE worksheet_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_id BIGINT NOT NULL,
    mini_game_id BIGINT NOT NULL,
    order_index INT NOT NULL,
    configuration JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT fk_worksheet_item_worksheet
        FOREIGN KEY (worksheet_id) REFERENCES worksheet(id) ON DELETE CASCADE,

    CONSTRAINT fk_worksheet_item_mini_game
        FOREIGN KEY (mini_game_id) REFERENCES mini_game_definition(id),

    CONSTRAINT uq_worksheet_item_order
        UNIQUE (worksheet_id, order_index)
);